name: Pull Github Merged file
on:
  workflow_dispatch:
    inputs:
      token:
        description: 'token'
        required: true
        default: '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'
        type: string
    branches:
      - main
jobs:
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Actions Ecosystem Action Get Merged Pull Request
        uses: actions-ecosystem/action-get-merged-pull-request@v1.0.1
        with:
          github_token: inputs.token


