name: Pull Github Merged file
on:
  workflow_dispatch:
    inputs:
      token:
        description: 'token'
        required: true
        default: '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'
        type: string
    branches:
      - main
jobs:
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Run Python Script
        run: python .github/workflows/action.py
        # env:
        #   SLACK_BOT_TOKEN : ${{ secrets.SLACK_BOT_TOKEN }}


